title: Eleni Schmitt
theme: jekyll-theme-minimal
description: 
  I am a student and soon-to-be developer based in Tulsa, Oklahoma.
  <br><br>
  <a href="https://www.linkedin.com/in/eleni-schmitt/">View My LinkedIn Profile</a> 
