title: Eleni Schmitt
theme: jekyll-theme-minimal
description: 
  I am a Development Analyst currently based in Tulsa, Oklahoma.
  <br><br><br>
  <a href="https://www.linkedin.com/in/eleni-schmitt/" target="_blank" rel="noopener noreferrer">View My LinkedIn Profile</a> 
